# Simple workflow for deploying static content to GitHub Pages
name: MAIN DEPLOY OMG

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ls -lsa
      - run: pwd
      - run: mkdir .public
      - run: cp -r * .public
      - run: mogrify -resize 40% .public/media/*.webp
      - run: gzip -k -9 -r .public
      - run: ls -lsa
      - run: pwd
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
